# Generated by Django 5.2.5 on 2025-08-18 16:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0002_initial'),
        ('school', '0002_delete_article'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.course'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='transaction',
            unique_together={('course', 'student')},
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['course', 'student', 'status'], name='operation_t_course__d4a74e_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['course', 'status'], name='operation_t_course__15adf1_idx'),
        ),
    ]
