# Generated by Django 5.2.5 on 2025-08-20 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_student_is_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='is_teacher',
        ),
    ]
