"""
Django settings for schoolia project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-vgtums^kz5+f2#9w==15l0-q&k$gua8rohfsbh6s75krjicqa9'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    'schoolia-app-456b3f26b08d.herokuapp.com',
    '.herokuapp.com',
    'localhost',
    '127.0.0.1',
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'authentication',
    'operation',
    'school',
    'article',
    'teacher',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    "django.middleware.locale.LocaleMiddleware",
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
MIDDLEWARE += [
    'school.middleware.CourseAccessMiddleware',
    'school.middleware.ManagerAccessMiddleware',
]

ROOT_URLCONF = 'schoolia.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.i18n'
            ],
        },
    },
]

TEMPLATES[0]['OPTIONS']['context_processors'] += [
    'school.course_context_processor.course_context',
]

WSGI_APPLICATION = 'schoolia.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         #'ENGINE': 'django.db.backends.sqlite3',
#         #'NAME': BASE_DIR / 'db.sqlite3',
#         'HOST' : 'n7qmaptgs6baip9z.chr7pe7iynqr.eu-west-1.rds.amazonaws.com',
#         'USERNAME' : 'fwc89wuhnzj9ddyw',
#         'PASSWORD' : 'nxoys9aebmkvkeni',
#         'PORT' : '3306',
#         'DATABASE' : 'x8doknpvurifbfhg',
#     }
# }

# import os
# import dj_database_url


# # parse الرابط دون ssl_require
# config = dj_database_url.parse(
#     os.environ['JAWSDB_MARIA_URL'],
#     conn_max_age=600,
# )

import os
import dj_database_url

DATABASES = {
    "default": dj_database_url.config(
        env="JAWSDB_MARIA_URL",          # هذا المتغير يضعه إضافة JawsDB Maria
        conn_max_age=600,
    )
}
# (اختياري) إعدادات آمنة/صارمة لـ MySQL/MariaDB
DATABASES["default"]["OPTIONS"] = {"init_command": "SET sql_mode='STRICT_TRANS_TABLES'"}


# # تخلّص من OPTIONS كلها حتى لا يمرر ssl_mode أو sslmode
# config.pop('OPTIONS', None)

# DATABASES['default'] = config #type:ignore






# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS = [
    BASE_DIR /'static',
]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

MEDIA_URL = f'https://{os.environ.get("AWS_STORAGE_BUCKET_NAME", '')}.s3.amazonaws.com/'#'/media/'


STRIPE_PUBLISHABLE_KEY = os.environ.get('STRIPE_PUBLISHABLE_KEY') #or secret_info1.STRIPE_PUBLISHABLE_KEY
STRIPE_SECRET_KEY = os.environ.get('STRIPE_SECRET_KEY') #or secret_info1.STRIPE_SECRET_KEY
STRIPE_ENDPOINT_SECRET = os.environ.get('STRIPE_ENDPOINT_SECRET') #or secret_info1.STRIPE_ENDPOINT_SECRET



CURRENCY = 'USD'


AUTH_USER_MODEL = "authentication.Student"


LOGIN_URL = 'login'  

LOGOUT_REDIRECT_URL = 'Index'

LOGIN_REDIRECT_URL = 'Index'


SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SECURE = True  
CSRF_COOKIE_SECURE = True     




LANGUAGE_CODE = "en"
LANGUAGES = [
    ("en", "English"),
    ("ar", "العربية"),
]

USE_I18N = True

LOCALE_PATHS = [BASE_DIR / "locale"]  # where .po/.mo live



CSRF_TRUSTED_ORIGINS = [
    "https://schoolia-app-456b3f26b08d.herokuapp.com",
    "https://*.herokuapp.com",
]
